name: Core SDK CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - support/SDK-V3
      - feature/**
      - bugfix/**
  pull_request:
    branches:
      - master
      - support/SDK-V3
      - feature/**
      - bugfix/**

jobs:
  tests:
    name: Tests
    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        xcode_version: [13.2.1]

    steps:
      - name: Get Sources
        uses: actions/checkout@v2

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '${{ matrix.xcode_version }}'

      - name: Update brew
      run: brew update

      - name: Update carthage
      run: brew upgrade carthage

      - name: Update carthage
      run: brew upgrade carthage

      - name: Install dependencies
      run: carthage update --platform ios --cache-builds --use-xcframeworks --no-use-binaries

      - name: Install test coverage reports tool - slather
      run: gem i slather

      - name: Install lint tool - swiftlint
      # Force to update the Swiftlint to the last stable version
      run: |
        brew outdated swiftlint || brew upgrade swiftlint
        wiftlint version

      - name: Install documentation tool - jazzy
      run: gem install jazzy

      - name: Run unit tests
      run:
        xcodebuild -enableCodeCoverage YES clean build test
          -project HyperwalletSDK.xcodeproj \
          -scheme "HyperwalletSDK" \
          -destination "platform=iOS Simulator,name=iPhone 13,OS=15.5" \
          -configuration Debug ONLY_ACTIVE_ARCH=YES ENABLE_TESTABILITY=YES CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

      - name: Lint validation
      run:
        # Lint - Add `--strict` to fail for warning and violation
        swiftlint lint --reporter json
