name: Core SDK CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - support/SDK-V3
      - feature/**
      - bugfix/**
  pull_request:
    branches:
      - master
      - support/SDK-V3
      - feature/**
      - bugfix/**

jobs:
  tests:
    name: Tests
    strategy:
      matrix:
        os: [macos-11, macos-latest, macos-10.15]
        xcode_version: [13.2.1]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '${{ matrix.xcode_version }}'
